apiVersion: 1

datasources:
  - name: PostGIS - Slope Susceptibility
    type: postgres
    access: proxy
    url: postgis_db:5432
    database: gisdb
    user: gis_user
    secureJsonData:
      password: gis_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true